name: sequence
description: "A Flutter application for [your app purpose]."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  playing_cards: ^0.4.1+11
  http: ^1.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  # image: "assets/icons/splash_logo.png"  # Removed until you add this file
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/logo.png
    # - assets/icons/splash_logo.png  # Uncomment when you add this file
    - assets/images/